# MACHINE-SPECIFIC FILE
#
# Replace this file with the one generated by:
#
#   nixos-generate-config --root /mnt
#
# during the NixOS installation.
#
# Do not blindly reuse this file for your LG Gram later:
# generate a separate hardware-configuration.nix for that machine.
#
# This placeholder intentionally fails if you try to build before replacing it.
{ ... }:

throw ''
  hardware-configuration.nix is still the placeholder.
  Generate the VM hardware configuration with:
    nixos-generate-config --root /mnt
  then copy /mnt/etc/nixos/hardware-configuration.nix here.
''
